ProjetoQLivros/ProjetoQLivros/Controllers/DoacaoController.cs
using ProjetoQLivros.Helpers.ViewModels;
using ProjetoQLivros.Models.BusinessController;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoQLivros.Controllers
{
    public class DoacaoController : Controller
    {
        DoacaoBusinessController doacaoBC = new DoacaoBusinessController();
        HistoricoBusinessController historicoBC = new HistoricoBusinessController();
        public ActionResult DadosReceptor(string email, string login, int idExemplar, int idDoador)
        {
            var result = doacaoBC.Doar(email, login, idExemplar, idDoador);

            if (result.Item1)
            {
                return View("~/Views/Doacao/ConfirmDoacao.cshtml", new Tuple<string,int>(result.Item2,idDoador));
            }
            else
            {
                var listaExemplares = historicoBC.VerificaPropriedade(idDoador);

                List<SelectListItem> opcoesExemplares = new List<SelectListItem>();

                foreach (var exemplar in listaExemplares.Item1)
                {
                    opcoesExemplares.Add(new SelectListItem { Text = String.Format("{0} - {1}ª Edição", exemplar.TabExemplar.TabTitulo.nmTitulo, exemplar.TabExemplar.dsEdicao), Value = exemplar.TabExemplar.idExemplar.ToString() });
                }

                DoacaoViewModel dadosRetorno = new DoacaoViewModel()
                {
                    Historicos = listaExemplares.Item1,
                    OpcoesExemplares = opcoesExemplares,
                    idDoador = idDoador,
                    Mensagem = result.Item2
                };

                return View("~/Views/Exemplar/FormDoar.cshtml",dadosRetorno);
            }
        }
    }
}

ProjetoQLivros/ProjetoQLivros/Controllers/ExemplarController.cs
using ProjetoQLivros.Helpers.ViewModels;
using ProjetoQLivros.Models.BusinessController;
using ProjetoQLivros.Models.TabModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ProjetoQLivros.Controllers
{
    public class ExemplarController : Controller
    {
        ExemplarBusinessController exemplarBC = new ExemplarBusinessController();
        HistoricoBusinessController historicoBC = new HistoricoBusinessController();
        LeitorBusinessController leitorBC = new LeitorBusinessController();

        public ActionResult Lista(string titulo)
        {
            var retornoLista = exemplarBC.FiltrarTitulo(titulo);
            if (retornoLista.Count() > 0)
            {
                return View(retornoLista);
            }
            else
            {
                ViewBag.SemLista = "Não há exemplares com esse título";
                return View("~/Views/Home/Index.cshtml");
            }
        }

        [HttpGet]
        [Route("exemplares/formdoar/{idLeitor}")]
        public ActionResult FormDoar(int idLeitor)
        {
            var result = historicoBC.VerificaPropriedade(idLeitor);
            if (result.Item2)
            {
                List<SelectListItem> opcoesExemplares = new List<SelectListItem>();

                foreach (var exemplar in result.Item1)
                {
                    opcoesExemplares.Add(new SelectListItem { Text = String.Format("{0} - {1}ª Edição", exemplar.TabExemplar.TabTitulo.nmTitulo,exemplar.TabExemplar.dsEdicao), Value = exemplar.TabExemplar.idExemplar.ToString() });
                }

                DoacaoViewModel dadosRetorno = new DoacaoViewModel()
                {
                    Historicos = result.Item1,
                    OpcoesExemplares = opcoesExemplares,
                    idDoador = idLeitor,
                    Mensagem = null
                };

                return View(dadosRetorno);
            }
            else
            {
                ViewBag.SemPropriedade = "Você não possui exemplares disponíveis para doar";
                return View("~/Views/Home/Index.cshtml",result.Item3);
            }
        }

        public ActionResult RomperCorrente(int idLeitor)
        {
            //Retorna uma lista com os exemplares que o leitor é proprietário.
            var result = exemplarBC.ObterPorLeitor(idLeitor);
            if (result.Item2)
            {
                return View(new Tuple<List<TabHistorico>, int>(result.Item1, idLeitor));
            }
            ViewBag.ErroRomper = "Não há exemplares para romper corrente";
            return View("~/Views/Home/Index.cshtml");
        }

        public ActionResult PesquisarExemplar(long idExemplar,int idLeitor)
        {
            var result = exemplarBC.ObterPorid(idExemplar);

            if (result.Item2)
            {
                return View("ConfirmRomper", new Tuple<TabExemplar,int>(result.Item1,idLeitor));
            }
            else
            {
                ViewBag.Romper = "Sua corrente não pode ser rompida! Há doação pendente. Espere o receptor elegível responder";
                return View("RomperCorrente");
            }

        }

        public ActionResult ExcluirExemplar(int idExemplar, string texto,int idLeitor)
        {
            var result = exemplarBC.Romper(idExemplar, texto);

            if (texto.Length > 10 && texto.Length < 200)
            {
                ViewBag.ErroObs = "A justificativa deve ter entre 10 a 200 caracteres";
                return View("ConfirmRomper", new Tuple<TabExemplar, int>(result.Item1, idLeitor));
            }
            else if (texto == "")
            {
                ViewBag.ErroObs = "Informe a justificativa";
                return View("ConfirmRomper", new Tuple<TabExemplar, int>(result.Item1, idLeitor));
            }
                
            return View("ConfirmSucessoRomper",new Tuple<String,int>(result.Item2,idLeitor));
        }

        public ActionResult FormDisponibilizar(int idLeitor)
        {
            var result = exemplarBC.ObterIndisponiveis(idLeitor);
            if (result.Item2)
            {
                return View(new Tuple<List<TabHistorico>,int>(result.Item1,idLeitor));
            }
            else
            {
                ViewBag.Disp = "Você não possui exemplares indisponíveis";
                return View("~/Views/Home/Index.cshtml");
            }

        }
        public ActionResult Disponibilizar (long idExemplar,int idLeitor)
        {
            var result = exemplarBC.ObterPorIdDisp(idExemplar);
            return View("ConfirmDisponibilizar",new Tuple<TabExemplar,int>(result,idLeitor));
        }

        public ActionResult AlterarStatus(long idExemplar,int idLeitor)
        {
            var msg = exemplarBC.Alterar(idExemplar);

            if (msg == "")
            {
                ViewBag.erro = "Esse exemplar está pendente";
                var result = exemplarBC.ObterIndisponiveis(idLeitor);
                return View("FormDisponibilizar", new Tuple<List<TabHistorico>, int>(result.Item1, idLeitor));
            }
            else
            {
                return PartialView("ConfirmSucessoDisponibilizar", new Tuple<String, int>(msg, idLeitor));
            }
        }

        public ActionResult ComecarCorrente(int idLeitor)
        {
            var leitor = leitorBC.Obter(idLeitor); 
            return View(new Tuple<TabExemplar,TabLeitor>(null,leitor));
        }

        public ActionResult Cadastrar(TabExemplar exemplar, string titulo,int idLeitor)
        {
            var leitor = leitorBC.Obter(idLeitor);
            if (ModelState.IsValid)
            {
                var result = exemplarBC.Criar(exemplar, titulo, idLeitor);
                return View("~/Views/Exemplar/ConfirmSucessoCriarExemplar.cshtml",new Tuple<String,int>(result.Item2,idLeitor));
            }
            return View("ComecarCorrente", new Tuple<TabExemplar, TabLeitor>(exemplar, leitor));
        }
    }
}

ProjetoQLivros/ProjetoQLivros/Controllers/ResenhaController.cs
using ProjetoQLivros.Models.BusinessController;
using ProjetoQLivros.Models.TabModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ProjetoQLivros.Controllers
{
    public class ResenhaController : Controller
    {
        ResenhaBusinessController resenhaBC = new ResenhaBusinessController();
        HistoricoBusinessController historicoBC = new HistoricoBusinessController();

        public ActionResult Lista(int idExemplar)
        {   
            var listaResenhas = resenhaBC.ObterPorExemplar(idExemplar);
            if (listaResenhas.Count() > 0)
            {
                return View(listaResenhas);
            }
            ViewBag.SemLista = "Não há resenhas para visualizar";
            return View("Index");
        }

        public ActionResult Info(int idResenha)
        {
            var result = resenhaBC.ObterConteudo(idResenha);
            return View(result);
        }

        public ActionResult FormResenha(int idLeitor)
        {
            var result = resenhaBC.VerificaPropriedade(idLeitor);

            List<SelectListItem> opcoesExemplares = new List<SelectListItem>();
            List<SelectListItem> opcoesTipoResenha = new List<SelectListItem>();

            if (result.Item2) 
            {
                foreach (var exemplar in result.Item1)
                {
                    opcoesExemplares.Add(new SelectListItem { Text = String.Format("{0} - {1}ª Edição", exemplar.TabExemplar.TabTitulo.nmTitulo, exemplar.TabExemplar.dsEdicao), Value = exemplar.TabExemplar.idExemplar.ToString() });
                }

                opcoesTipoResenha.Add(new SelectListItem { Text = "Conteúdo", Value = "1" });
                opcoesTipoResenha.Add(new SelectListItem { Text = "Estado de uso", Value = "2" });

                return View("~/Views/Resenha/FormResenha.cshtml", new Tuple<List<SelectListItem>,List<SelectListItem>,int>(opcoesExemplares,opcoesTipoResenha,idLeitor));
            }
            else
            {
                ViewBag.ErroResenha = "Você não é proprietário de nenhum exemplar. Impossível publicar resenha";
                return View("~/Views/Home/Index.cshtml");
            }
        }
            
        public ActionResult Publicar(TabResenha resenha,int idLeitor)
        {
            resenhaBC.Criar(resenha);
            return View("~/Views/Resenha/ConfirmPublicacao.cshtml",new Tuple<String,int>("Resenha publicada com sucesso",idLeitor));
        }
    }
}

ProjetoQLivros/ProjetoQLivros/Views/Exemplar/ComecarCorrente.cshtml
@model Tuple<TabExemplar,TabLeitor>
@{
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

@using (Ajax.BeginForm("Cadastrar", "Exemplar", FormMethod.Post, new AjaxOptions() { UpdateTargetId = "qlivros-modal-content", OnSuccess = "QLivrosModal", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "" }))
{
    @Html.Hidden("idLeitor", Model.Item2.idLeitor)
    <h1>Comece uma corrente</h1>
    <h4 class="text-left content-brief">Informe os dados do exemplar que você deseja começar uma corrente para que os demais leitores possam pesquisa-lo dentro do QLivros.</h4>
    <fieldset class="text-left">
        <div class="form-group">
            @Html.TextBox("titulo", null, null, new { @class = "form-control", placeholder = "Título", type = "text", required = "required", oninvalid = "this.setCustomValidity('Entre com o título')", oninput = "setCustomValidity('')" })
        </div>
        <div class="form-group">
            @Html.TextBox("nmAutor", null, null, new { @class = "form-control", placeholder = "Autor", type = "text", required = "required", oninvalid = "this.setCustomValidity('Entre com o nome do autor')", oninput = "setCustomValidity('')" })
        </div>
        <div class="form-group">
            @Html.TextBox("nmEditora", null, null, new { @class = "form-control", placeholder = "Editora", type = "text", required = "required", oninvalid = "this.setCustomValidity('Entre com o nome da editora')", oninput = "setCustomValidity('')" })
        </div>
        <div class="form-group">
            @Html.TextBox("dsEdicao", null, null, new { @class = "form-control", placeholder = "Edição", type = "text", required = "required", oninvalid = "this.setCustomValidity('Entre com a edição do exemplar')", oninput = "setCustomValidity('')" })
        </div>
    </fieldset>
    <br />
    <input type="submit" class="btn btn-blue" value="Começar corrente" />
    <input type="reset" class="btn btn-default btn-md" value="Limpar">
}

        

ProjetoQLivros/ProjetoQLivros/Views/Exemplar/ConfirmDisponibilizar.cshtml
@model Tuple<TabExemplar,int>
@{
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="modal-content bs-callout bs-callout-danger">
    <div class="modal-header">
        
        <h3 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-book"></span> Disponibilizar Exemplar</h3>
    </div>
    <div class="modal-body">
        <p class="lead">Deseja mesmo disponibilizar o exemplar ?</p>
        <p><small>Se o fizer, não será mais possível torná-lo indisponível</small><br />
            <small>caso queria continuar a leitura.</small>
        </p>

        <strong>Título:</strong>@Model.Item1.TabTitulo.nmTitulo<br>
        <strong>Autor:</strong>@Model.Item1.nmAutor<br>
        <strong>Editora:</strong>@Model.Item1.nmEditora<br>
        <strong>Edição: </strong>@Model.Item1.dsEdicao

    </div>

    <div class="modal-footer text-right">

        @Ajax.ActionLink("Sim, disponibilizar", "AlterarStatus", "Exemplar", new { idExemplar = @Model.Item1.idExemplar,idLeitor = @Model.Item2 },
        new AjaxOptions()
        {
            HttpMethod = "Post",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "qlivros-modal-content",
            OnSuccess = "QLivrosModal",
        }, new { @class = "btn btn-primary" })


        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="location.reload()">Cancelar</button>

    </div>

</div>

ProjetoQLivros/ProjetoQLivros/Views/Exemplar/ConfirmRomper.cshtml
@model Tuple<TabExemplar, int>
@{
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="modal-content bs-callout bs-callout-danger">
    <div class="modal-header">

        <h3 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-book"></span> Romper corrente</h3>
    </div>
    <div class="modal-body">
        <p class="lead">Justifique o motivo do rompimento</p>
        @using (Ajax.BeginForm("ExcluirExemplar", "Exemplar", new { idExemplar = @Model.Item1.idExemplar, idLeitor = @Model.Item2 },
        new AjaxOptions()
        {
            HttpMethod = "Post",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "qlivros-modal-content",
            OnSuccess = "QLivrosModal",
        }, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="form-group">
                <div class="col-sm-12">
                    @Html.TextArea("texto", new { @class = "form-control", id = "input-nome-psettings", placeholder = "Ex: Entre com sua justificativa", rows = 3 })
                    
                </div>
            </div>

            <button id="s9ads-btn-create-psettings" type="submit" class="btn btn-primary btn-sm" data-loading-text="Aguarde..." autocomplete="off">
                <span class="glyphicon glyphicon-remove"></span> Romper Corrente
            </button>

            <button type="button" class="btn btn-default" data-dismiss="modal" onclick="location.reload()">Cancelar</button>

           
        }

    </div>
</div>

ProjetoQLivros/ProjetoQLivros/Views/Exemplar/ConfirmSucessoCriarExemplar.cshtml
@model Tuple<String, int>
@{
    ViewBag.Title = "ConfirmSucessoCriarExemplar";
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}
<div class="modal-content bs-callout bs-callout-danger">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true" onclick="location.href = '@Url.Action("Index","Home",new{idLeitor = Model.Item2}) '">&times;</span>
            <span class="sr-only">Fechar</span>
        </button>
    </div>
    <div class="modal-body">
        <h3>@Model.Item1</h3>
    </div>


</div>

ProjetoQLivros/ProjetoQLivros/Views/Exemplar/ConfirmSucessoDisponibilizar.cshtml
@model Tuple<String,int>

@{
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="modal-content bs-callout">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true" onclick="location.href = '@Url.Action("Index","Home",new{idLeitor = Model.Item2}) '">&times;</span><span class="sr-only">Fechar</span></button>
        <h3>@Model.Item1</h3>
    </div>
</div>

ProjetoQLivros/ProjetoQLivros/Views/Exemplar/ConfirmSucessoRomper.cshtml
@model Tuple<String, int>

@{
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="modal-content bs-callout">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true" onclick="location.href = '@Url.Action("Index","Home",new{idLeitor = Model.Item2}) '">&times;</span><span class="sr-only">Fechar</span></button>
        <h3>@Model.Item1</h3>
    </div>
</div>

ProjetoQLivros/ProjetoQLivros/Views/Exemplar/FormDisponibilizar.cshtml
@model Tuple<List<TabHistorico>,int>
@{
    ViewBag.Title = "FormDisponibilizar";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

<h1>Disponibilizar exemplar</h1>
<h4 class="text-left content-brief">Selecione o exemplar que você deseja disponibilizar para que os demais leitores possam pesquisa-lo dentro do QLivros.</h4>
<div class="list-group">
    @foreach (var registro in Model.Item1)
    {
        @Ajax.ActionLink(String.Format("{0} - {1}ª Edição", @registro.TabExemplar.TabTitulo.nmTitulo, @registro.TabExemplar.dsEdicao), "Disponibilizar", "Exemplar", new { idExemplar = registro.fkIdExemplar, idLeitor = Model.Item2 }, new AjaxOptions() { UpdateTargetId = "qlivros-modal-content", OnSuccess = "QLivrosModal", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "list-group-item" })
    }

</div>

@if (ViewBag.erro != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.erro
    </div>
}

ProjetoQLivros/ProjetoQLivros/Views/Exemplar/FormDoar.cshtml
@model DoacaoViewModel
@{
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

@using (Ajax.BeginForm("DadosReceptor", "Doacao", FormMethod.Post, new AjaxOptions() { UpdateTargetId = "qlivros-modal-content", OnSuccess = "QLivrosModal", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "" }))
{
   @Html.Hidden("idDoador", Model.idDoador)

    <h1>Doe um exemplar</h1>
    <h4 class="text-left content-brief">Selecione o exemplar que você deseja doar e os dados respectivos do receptor para que a solicitação de doação seja enviada.</h4>
    <section class="donate">
        <form class="text-center">
            @if (Model.Mensagem != null)
            {
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    @Model.Mensagem
                </div>
            }
            <div class="form-group">
                @Html.DropDownList("idExemplar", Model.OpcoesExemplares, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.TextBox("email", null, null, new { @class = "form-control", placeholder = "Entre com o email do receptor", type = "email", required = "required", oninvalid = "this.setCustomValidity('Entre com o Email do Receptor')", oninput = "setCustomValidity('')" })
            </div>
            <div class="form-group">
                @Html.TextBox("login", null, null, new { @class = "form-control", placeholder = "Entre com o login do receptor", type = "text", required = "required", oninvalid = "this.setCustomValidity('Entre com o login do receptor')", oninput = "setCustomValidity('')" })
            </div>
            <button type="submit" class="btn btn-blue">Doar exemplar</button>
        </form>
    </section>
}

ProjetoQLivros/ProjetoQLivros/Views/Exemplar/Lista.cshtml
@model List<TabHistorico>

@{
    ViewBag.Title = "Lista";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Lista", "Exemplar", FormMethod.Post, new { }))
{

    <div class="main-block main-search">
        <section class="search">
            <div class="input-group">
                @Html.TextBox("titulo", null, new { @class = "form-control", id = "input-titulo", placeholder = "Digite o título a ser pesquisado" })
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
            @if (ViewBag.SemLista != null)
            {
                <div class="alert alert-danger" role="alert">
                    @ViewBag.SemLista
                </div>
            }
            else
            {
                <div class="panel-group results" id="accordion">
                    <h3 class="text-left">Resultado da pesquisa:</h3>
                    @foreach (var item in Model)
                    {
                        <div class="panel panel-default">
                            <a class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#@item.idHistorico">
                                @item.TabExemplar.TabTitulo.nmTitulo -
                                @item.TabLeitor.TabLogradouroEnd.TabBairro.TabCidade.TabEstado.nmEstado
                                <span class="glyphicon glyphicon-option-horizontal"></span>
                            </a>
                            <div id="@item.idHistorico" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-md-6 book-info">
                                            <div class="row panel-content-header"><h4><strong>Informações do Livro:</strong></h4></div>
                                            <div class="row"><strong>Título: </strong>@item.TabExemplar.TabTitulo.nmTitulo</div>
                                            <div class="row"><strong>Autor: </strong>@item.TabExemplar.nmAutor</div>
                                            <div class="row"><strong>Edição: </strong>@item.TabExemplar.dsEdicao</div>
                                            <div class="row"><strong>Editora: </strong>@item.TabExemplar.nmEditora</div>
                                            <div class="row">@Html.ActionLink(String.Format("Resenhas: {0}", @item.TabExemplar.TabResenha.Count().ToString()), "Lista", "Resenha", new { idExemplar = @item.TabExemplar.idExemplar }, new { style = "font-weight:bold" })</div>
                                        </div>
                                        <div class="col-md-6 book-owner">
                                            <div class="row panel-content-header"><h4><strong>Informações do Proprietário:</strong></h4></div>
                                            <div class="row"><strong>Login: </strong>@item.TabLeitor.dsLogin</div>
                                            <div class="row"><strong>Email: </strong>@item.TabLeitor.dsEmail</div>
                                            <div class="row"><strong>Celular: </strong>@item.TabLeitor.numCel</div>
                                            <div class="row">
                                                <strong>Local: </strong>
                                                @item.TabLeitor.TabLogradouroEnd.TabBairro.TabCidade.TabEstado.nmEstado,
                                                @item.TabLeitor.TabLogradouroEnd.TabBairro.TabCidade.nmCidade -
                                                @item.TabLeitor.TabLogradouroEnd.TabBairro.nmBairro
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        }
                    
                </div>
            }
        </section>
    </div>
}

ProjetoQLivros/ProjetoQLivros/Views/Exemplar/RomperCorrente.cshtml
@model Tuple<List<TabHistorico>,int>
@{
    ViewBag.Title = "RomperCorrente";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

<h1>Romper Corrente</h1>
<h4 class="text-left content-brief">Selecione um exemplar para romper corrente. Dessa forma, ele não poderá mais ser pesquisado pelos demais leitores.</h4>
<div class="list-group">
    @foreach (var registro in Model.Item1)
    {
        @Ajax.ActionLink(String.Format("{0} - {1}ª Edição", @registro.TabExemplar.TabTitulo.nmTitulo, @registro.TabExemplar.dsEdicao), "PesquisarExemplar", "Exemplar", new { idExemplar = registro.fkIdExemplar, idLeitor = Model.Item2 }, new AjaxOptions() { UpdateTargetId = "qlivros-modal-content", OnSuccess = "QLivrosModal", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "list-group-item" })
    }

</div>

@if (ViewBag.erro != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.erro
    </div>
}