ProjetoQLivros/ProjetoQLivros/Controllers/ExemplarController.cs
using ProjetoQLivros.Helpers.ViewModels;
using ProjetoQLivros.Models.BusinessController;
using ProjetoQLivros.Models.TabModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ProjetoQLivros.Controllers
{
    public class ExemplarController : Controller
    {
        ExemplarBusinessController exemplarBC = new ExemplarBusinessController();
        HistoricoBusinessController historicoBC = new HistoricoBusinessController();
        LeitorBusinessController leitorBC = new LeitorBusinessController();

        public ActionResult Lista(string titulo)
        {
            var retornoLista = exemplarBC.FiltrarTitulo(titulo);
            if (retornoLista.Count() > 0)
            {
                return View(retornoLista);
            }
            else
            {
                ViewBag.SemLista = "Não há exemplares com esse título";
                return View("~/Views/Home/Index.cshtml");
            }
        }

        [HttpGet]
        [Route("exemplares/formdoar/{idLeitor}")]
        public ActionResult FormDoar(int idLeitor)
        {
            var result = historicoBC.VerificaPropriedade(idLeitor);
            if (result.Item2)
            {
                List<SelectListItem> opcoesExemplares = new List<SelectListItem>();

                foreach (var exemplar in result.Item1)
                {
                    opcoesExemplares.Add(new SelectListItem { Text = String.Format("{0} - {1}ª Edição", exemplar.TabExemplar.TabTitulo.nmTitulo,exemplar.TabExemplar.dsEdicao), Value = exemplar.TabExemplar.idExemplar.ToString() });
                }

                DoacaoViewModel dadosRetorno = new DoacaoViewModel()
                {
                    Historicos = result.Item1,
                    OpcoesExemplares = opcoesExemplares,
                    idDoador = idLeitor,
                    Mensagem = null
                };

                return View(dadosRetorno);
            }
            else
            {
                ViewBag.SemPropriedade = "Você não possui exemplares disponíveis para doar";
                return View("~/Views/Home/Index.cshtml",result.Item3);
            }
        }

        public ActionResult RomperCorrente(int idLeitor)
        {
            //Retorna uma lista com os exemplares que o leitor é proprietário.
            var result = exemplarBC.ObterPorLeitor(idLeitor);
            if (result.Item2)
            {
                return View(new Tuple<List<TabHistorico>, int>(result.Item1, idLeitor));
            }
            ViewBag.ErroRomper = "Não há exemplares para romper corrente";
            return View("~/Views/Home/Index.cshtml");
        }

        public ActionResult PesquisarExemplar(long idExemplar,int idLeitor)
        {
            var result = exemplarBC.ObterPorid(idExemplar);

            if (result.Item2)
            {
                return View("ConfirmRomper", new Tuple<TabExemplar,int>(result.Item1,idLeitor));
            }
            else
            {
                ViewBag.Romper = "Sua corrente não pode ser rompida! Há doação pendente. Espere o receptor elegível responder";
                return View("RomperCorrente");
            }

        }

        public ActionResult ExcluirExemplar(int idExemplar, string texto,int idLeitor)
        {
            var result = exemplarBC.Romper(idExemplar, texto);

            if (texto.Length > 10 && texto.Length < 200)
            {
                ViewBag.ErroObs = "A justificativa deve ter entre 10 a 200 caracteres";
                return View("ConfirmRomper", new Tuple<TabExemplar, int>(result.Item1, idLeitor));
            }
            else if (texto == "")
            {
                ViewBag.ErroObs = "Informe a justificativa";
                return View("ConfirmRomper", new Tuple<TabExemplar, int>(result.Item1, idLeitor));
            }
                
            return View("ConfirmSucessoRomper",new Tuple<String,int>(result.Item2,idLeitor));
        }

        public ActionResult FormDisponibilizar(int idLeitor)
        {
            var result = exemplarBC.ObterIndisponiveis(idLeitor);
            if (result.Item2)
            {
                return View(new Tuple<List<TabHistorico>,int>(result.Item1,idLeitor));
            }
            else
            {
                ViewBag.Disp = "Você não possui exemplares indisponíveis";
                return View("~/Views/Home/Index.cshtml");
            }

        }
        public ActionResult Disponibilizar (long idExemplar,int idLeitor)
        {
            var result = exemplarBC.ObterPorIdDisp(idExemplar);
            return View("ConfirmDisponibilizar",new Tuple<TabExemplar,int>(result,idLeitor));
        }

        public ActionResult AlterarStatus(long idExemplar,int idLeitor)
        {
            var msg = exemplarBC.Alterar(idExemplar);

            if (msg == "")
            {
                ViewBag.erro = "Esse exemplar está pendente";
                var result = exemplarBC.ObterIndisponiveis(idLeitor);
                return View("FormDisponibilizar", new Tuple<List<TabHistorico>, int>(result.Item1, idLeitor));
            }
            else
            {
                return PartialView("ConfirmSucessoDisponibilizar", new Tuple<String, int>(msg, idLeitor));
            }
        }

        public ActionResult ComecarCorrente(int idLeitor)
        {
            var leitor = leitorBC.Obter(idLeitor); 
            return View(new Tuple<TabExemplar,TabLeitor>(null,leitor));
        }

        public ActionResult Cadastrar(TabExemplar exemplar, string titulo,int idLeitor)
        {
            var leitor = leitorBC.Obter(idLeitor);
            if (ModelState.IsValid)
            {
                var result = exemplarBC.Criar(exemplar, titulo, idLeitor);
                return View("~/Views/Exemplar/ConfirmSucessoCriarExemplar.cshtml",new Tuple<String,int>(result.Item2,idLeitor));
            }
            return View("ComecarCorrente", new Tuple<TabExemplar, TabLeitor>(exemplar, leitor));
        }
    }
}

ProjetoQLivros/ProjetoQLivros/Controllers/HistoricoController.cs
using ProjetoQLivros.Models.BusinessController;
using ProjetoQLivros.Models.TabModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ProjetoQLivros.Controllers
{
    public class HistoricoController : Controller
    {
        HistoricoBusinessController historicoBC = new HistoricoBusinessController();
        NotificacaoBusinessController notificacaoBC = new NotificacaoBusinessController();
        public ActionResult AcompanharHistorico(long idLeitor)
        {

            if (historicoBC.ObterLidos(idLeitor).Count() == 0)
            {
                ViewBag.HistNulo = "Você não possui históricos.";
                return View("~/Views/Home/Index.cshtml");
            }
            else
            {
                return View(historicoBC.ObterLidos(idLeitor));
            }
        }
        public ActionResult VisualizarHistorico(long idExemplar)
        {
            var historico = historicoBC.ListaHistorico(idExemplar);
            return View("VisualizarHistorico", historico);
        }

        public ActionResult Lista(int idLeitor)
        {
            var lista = notificacaoBC.ObterLista(idLeitor);
            Session["notificacao"] = "NAO";
            return View(lista);
        }

        public ActionResult Info(int idHistorico)
        {
            var notificacao = notificacaoBC.Detalhes(idHistorico);
            return View(notificacao);
        }

        public ActionResult Resultado(int idReceptor,int idDoador, int idExemplar, string resposta)
        {
            var resultado = historicoBC.VerificaResposta(idReceptor, idDoador, idExemplar, resposta);
            return PartialView("RespNotificacao", new Tuple<string,int>(resultado,idReceptor));
        }

        public ActionResult ListaRanking(long idLeitor)
        {
            List<TabHistorico> retornoLeitores = historicoBC.RankingLeitores(idLeitor);
            List<TabHistorico> retornoExemplares = historicoBC.RankingExemplares();

            var Posicao = retornoLeitores.Where(model => model.fkIdLeitor == idLeitor).FirstOrDefault();
            if (Posicao != null)
            {
                ViewBag.Pos = Posicao;
            }
            else
            {
                ViewBag.Pos = "Não Classificado ainda";
            }

            ViewBag.Leitor = retornoLeitores;
            ViewBag.Livro = retornoExemplares;

            return View();
        }
    }
}

ProjetoQLivros/ProjetoQLivros/Controllers/LeitorController.cs
using ProjetoQLivros.Models.BusinessController;
using ProjetoQLivros.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using ProjetoQLivros.Models.TabModels;

namespace ProjetoQLivros.Controllers
{
    public class LeitorController : Controller
    {
        LeitorBusinessController leitorBC = new LeitorBusinessController();
        [HttpPost]
        [Route("qlivros/login")]
        public ActionResult Autenticar(TabLeitor leitor)
        {
            if (ModelState.IsValid)
            {
                var result = leitorBC.VerificaLogin(leitor);

                if (result.Item2)
                {
                    Session["usuario"] = result.Item1;
                    return RedirectToAction("Index", "Home", new { idLeitor = result.Item1.idLeitor });
                }
                else
                {
                    ViewBag.ErroAutentica = "Login ou senha incorretos";
                    return View("~/Views/Home/Login.cshtml");
                }
            }
            return View("~/Views/Home/Login.cshtml");
        }

        public ActionResult ConfirmCancelamento()
        {
            return View("~/Views/Leitor/ConfirmCancelamento.cshtml");
        }

        public ActionResult FormCadastro()
        {
            return View();
        }

        public ActionResult Cadastrar(TabLeitor leitor,string rua,string bairro,string cidade,string estado)
        {
            var _leitor = leitorBC.CadastrarLeitor(leitor, rua, bairro, cidade, estado);

            if (_leitor == null)
            {
                ViewBag.StatusCadastro = "Erro na hora do cadastro";
                return View();
            }
            else
            {
                ViewBag.SucessoCadastro = "Cadastro realizado com sucesso.";
                return View("~/Views/Leitor/ConfirmSucessoCadastro.cshtml");
            }
        }
    }
}

ProjetoQLivros/ProjetoQLivros/Controllers/ResenhaController.cs
using ProjetoQLivros.Models.BusinessController;
using ProjetoQLivros.Models.TabModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ProjetoQLivros.Controllers
{
    public class ResenhaController : Controller
    {
        ResenhaBusinessController resenhaBC = new ResenhaBusinessController();
        HistoricoBusinessController historicoBC = new HistoricoBusinessController();

        public ActionResult Lista(int idExemplar)
        {   
            var listaResenhas = resenhaBC.ObterPorExemplar(idExemplar);
            if (listaResenhas.Count() > 0)
            {
                return View(listaResenhas);
            }
            ViewBag.SemLista = "Não há resenhas para visualizar";
            return View("Index");
        }

        public ActionResult Info(int idResenha)
        {
            var result = resenhaBC.ObterConteudo(idResenha);
            return View(result);
        }

        public ActionResult FormResenha(int idLeitor)
        {
            var result = resenhaBC.VerificaPropriedade(idLeitor);

            List<SelectListItem> opcoesExemplares = new List<SelectListItem>();
            List<SelectListItem> opcoesTipoResenha = new List<SelectListItem>();

            if (result.Item2) 
            {
                foreach (var exemplar in result.Item1)
                {
                    opcoesExemplares.Add(new SelectListItem { Text = String.Format("{0} - {1}ª Edição", exemplar.TabExemplar.TabTitulo.nmTitulo, exemplar.TabExemplar.dsEdicao), Value = exemplar.TabExemplar.idExemplar.ToString() });
                }

                opcoesTipoResenha.Add(new SelectListItem { Text = "Conteúdo", Value = "1" });
                opcoesTipoResenha.Add(new SelectListItem { Text = "Estado de uso", Value = "2" });

                return View("~/Views/Resenha/FormResenha.cshtml", new Tuple<List<SelectListItem>,List<SelectListItem>,int>(opcoesExemplares,opcoesTipoResenha,idLeitor));
            }
            else
            {
                ViewBag.ErroResenha = "Você não é proprietário de nenhum exemplar. Impossível publicar resenha";
                return View("~/Views/Home/Index.cshtml");
            }
        }
            
        public ActionResult Publicar(TabResenha resenha,int idLeitor)
        {
            resenhaBC.Criar(resenha);
            return View("~/Views/Resenha/ConfirmPublicacao.cshtml",new Tuple<String,int>("Resenha publicada com sucesso",idLeitor));
        }
    }
}

ProjetoQLivros/ProjetoQLivros/Views/Shared/Modal.cshtml
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="table">
        <div class="modal-dialog modal-vertical-centered" role="document" id="qlivros-modal-content">

        </div>
    </div>
</div>

ProjetoQLivros/ProjetoQLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>QLivros</title>
    <meta name="description" content="QLivros - Doação e troca de livros" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link href="~/Content/css/navmenu-reveal.css" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/css/bootstrap.custom.css" />
    <link rel="stylesheet" href="~/Content/css/styles.css" />
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>
</head>
<body>
    <!--MENU SUPERIOR-->
    <div class="container-fluid login-content">
        <section class="row text-center">
            <div class="col-xs-12 main-content-login">
                <div class="main-block main-login">
                    @RenderBody()
                </div>
            </div>
        </section>
        
    </div>
    @Html.Partial("Modal")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/js/qlivros-modal.js"></script>
    <script src="~/Content/js/jquery-2.1.4.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/jasny-bootstrap.min.js"></script>
    <script src="~/Content/js/qlivros-modal.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

ProjetoQLivros/ProjetoQLivros/Views/Shared/_LayoutInterno.cshtml
@{
    var usuarioAtual = Session["usuario"] as TabLeitor;
    var notificacao = Session["notificacao"] as string;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>QLivros</title>
    <meta name="description" content="QLivros - Doação e troca de livros" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link href="~/Content/css/jasny-bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/navmenu-reveal.css" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/css/bootstrap.custom.css" />
    <link rel="stylesheet" href="~/Content/css/styles.css" />
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>
</head>
<body>
    <!--MENU LATERAL-->
    <div class="navmenu navmenu-default navmenu-fixed-left">
        <div class="navmenu-brand" href="#">Menu Principal</div>
        <ul class="nav navmenu-nav">
            <li>@Html.IconActionLink("glyphicon glyphicon-search","Pesquisar exemplares","Index","Home",new{idLeitor = usuarioAtual.idLeitor},new{})</li>
            <li>@Html.IconActionLink("glyphicon glyphicon-share","Comece uma corrente","ComecarCorrente","Exemplar",new{idLeitor = usuarioAtual.idLeitor},new{}) </li>
            
            <li>@Html.IconActionLink("glyphicon glyphicon-arrow-right glyphicon", "Doar exemplar", "FormDoar", "Exemplar", new { idLeitor = usuarioAtual.idLeitor }, new { })</li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#exemplares">
                    Meus exemplares
                    <span class="glyphicon glyphicon-book"></span>
                </a>
                <ul class="dropdown-menu navmenu-nav">
                    <li>
                        @Html.IconActionLink("glyphicon glyphicon-lock", "Romper corrente", "RomperCorrente", "Exemplar", new { idLeitor = usuarioAtual.idLeitor }, new { })
                    </li>
                    <li>
                        @Html.IconActionLink("glyphicon glyphicon-ok", "Disponibilizar exemplar", "FormDisponibilizar", "Exemplar", new { idLeitor = usuarioAtual.idLeitor }, new { })
                    </li>
                </ul>
            </li>
            <li>@Html.IconActionLink("glyphicon glyphicon-flag", "Acompanhar histórico", "AcompanharHistorico", "Historico", new { idLeitor = usuarioAtual.idLeitor }, new { })</li>
            <li>@Html.IconActionLink("glyphicon glyphicon-star", "Verificar Ranking", "ListaRanking", "Historico", new { idLeitor = usuarioAtual.idLeitor }, new { })</li>
            <li>@Html.IconActionLink("glyphicon glyphicon-file", "Publicar resenha", "FormResenha", "Resenha", new { idLeitor = usuarioAtual.idLeitor }, new { })</li>
            <li><a href="#section8">Chat<span class="glyphicon glyphicon-comment"></span></a></li>
            <li><a href="#section4">Meus dados<span class="glyphicon glyphicon-th-list"></span></a></li>
           
            <li>@Ajax.ActionLink("Cancelar participação", "ConfirmCancelamento", "Leitor", new { }, new AjaxOptions() { UpdateTargetId = "qlivros-modal-content", OnSuccess = "QLivrosModal", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" })</li>
            <li>@Html.IconActionLink("glyphicon glyphicon-off","Sair","Login","Home",new{},new{})</li>

        </ul>
    </div>

    <!--MENU SUPERIOR-->
    <div class="canvas">
        <div class="navbar navbar-blue navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle navbar-toggle-blue" data-toggle="offcanvas" data-recalc="false" data-target=".navmenu" data-canvas=".canvas">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="navbar-collapsible">
                <ul class="nav navbar-nav navbar-left">
                    <li>@Html.IconActionLink("glyphicon glyphicon-search", "Pesquisar exemplares", "Index", "Home", new { idLeitor = usuarioAtual.idLeitor }, new { })</li>
                    <li>@Html.IconActionLink("glyphicon glyphicon-share", "Comece uma corrente", "ComecarCorrente", "Exemplar", new { idLeitor = usuarioAtual.idLeitor }, new { }) </li>
                
                    <li>@Html.IconActionLink("glyphicon glyphicon-arrow-right glyphicon", "Doar exemplar", "FormDoar", "Exemplar", new { idLeitor = usuarioAtual.idLeitor }, new { })</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#exemplares">
                            Meus exemplares
                            <span class="glyphicon glyphicon-book"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.IconActionLink("glyphicon glyphicon-lock", "Romper corrente", "RomperCorrente", "Exemplar", new { idLeitor = usuarioAtual.idLeitor }, new { })
                            </li>
                            <li>
                                @Html.IconActionLink("glyphicon glyphicon-ok", "Disponibilizar exemplar", "FormDisponibilizar", "Exemplar", new { idLeitor = usuarioAtual.idLeitor }, new { })
                            </li>
                        </ul>
                    </li>
                    <li>@Html.IconActionLink("glyphicon glyphicon-flag", "Acompanhar histórico", "AcompanharHistorico", "Historico", new { idLeitor = usuarioAtual.idLeitor }, new { })</li>
                    <li>@Html.IconActionLink("glyphicon glyphicon-star", "Verificar Ranking", "ListaRanking", "Historico", new { idLeitor = usuarioAtual.idLeitor }, new { })</li>
                    <li>@Html.IconActionLink("glyphicon glyphicon-file", "Publicar resenha", "FormResenha", "Resenha", new { idLeitor = usuarioAtual.idLeitor }, new { })</li>
                    <li><a href="#section8">Chat<span class="glyphicon glyphicon-comment"></span></a></li>
                    <li><a href="#section4">Meus dados<span class="glyphicon glyphicon-th-list"></span></a></li>
                    <li>@Ajax.ActionLink("Cancelar participação", "ConfirmCancelamento", "Leitor", new { }, new AjaxOptions() { UpdateTargetId = "qlivros-modal-content",OnSuccess="QLivrosModal", InsertionMode = InsertionMode.Replace,HttpMethod= "GET" })</li>
                    <li>@Html.IconActionLink("glyphicon glyphicon-off", "Sair", "Login", "Home", new { }, new { })</li>

                </ul>
            </div>
        </div>
        <div class="container-fluid center-content">
            <header class="row header-main">
                <div class="col-xs-12 text-right">
                    @if (notificacao == "SIM")
                    {
                        @Html.IconActionLink("glyphicon glyphicon-envelope", "Lista", "Historico", new { idLeitor = usuarioAtual.idLeitor }, new { })
                    }
                    <div class="user">
                        <a href="#dados" id="logout">
                            Olá, @usuarioAtual.dsLogin
                            <span class="glyphicon glyphicon-user"></span>
                        </a>
                    </div>
                </div>
            </header>
            <section class="row text-center section-main">
                <div class="col-xs-12 main-content">
                    <div class="main-block main-search">
                        @RenderBody()
                    </div>
                </div>
            </section>
            <footer class="row footer-main">
                <small class="copyright">Copyright ® 2015 - QLivros. Todos os direitos reservados. All rights reserved.</small>
            </footer>
        </div>
    </div>
    @Html.Partial("Modal")
    <script src="~/Content/js/jquery-2.1.4.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/jasny-bootstrap.min.js"></script>
    <script src="~/Content/js/qlivros-modal.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
</body>
</html>

ProjetoQLivros/ProjetoQLivros/Views/Shared/_LayoutModal.cshtml
    <div class="container-fluid">
        <section class="row text-center">
            <div class="col-xs-12">
                @RenderBody()
            </div>
        </section>
    </div>
    @Scripts.Render("~/bundles/bootstrap")